# Generated by Django 3.1.4 on 2020-12-30 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator('Invalid Email')], verbose_name='email address')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='First name is too short'), django.core.validators.MaxLengthValidator(15, message='First name is too long')], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='Last name is too short'), django.core.validators.MaxLengthValidator(15, message='Last name is too long')], verbose_name='Last Name')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_merchant', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
